<style type="text/css">
    #logger  {
        width:800px;
        margin: 0 auto;
        border-collapse: collapse;
        font-family: Arial, Helvetica, sans-serif; 
    }
    #logger td, #logger th {
        border: 1px solid black;
        padding: 4px;
    }
    .key { text-align: center; width: 150px; }

</style>

<?php if (count($this->messages)) : ?>
<ul id="messages">
<?php foreach ($this->messages as $message) : ?>
    <li><?php echo $this->escape($message); ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<table id='logger'>
    <tr>
        <th>Timestamp</th>
        <th>Message</th>
        <th>Priority Name</th>
        <th>Module</th>
        <th>Controller</th>
    </tr>
<?php
foreach ($this->docs as $d) {
    if (isset($d['timestamp'])) {
        echo "<tr>";
        echo "<td>".$d['timestamp']."</td>";
        echo "<td>".$d['message']."</td>";
        echo "<td>".$d['priorityName']."</td>";
        echo "<td>".$d['module']."</td>";
        echo "<td>".$d['controller']."</td>";
        echo "</tr>";
    }
}
echo "</table>";

echo "<br />";
echo "Create some log messages by this links: ";
foreach ($this->priorities as $k => $v) {
    echo "<a href='".$this->url(array("controller"=>"index", "action"=>"log", "id"=>$k))."'>$v</a> ";
}